version: '3'
services:
  mongodb:
    image: mongo:3.4.22-xenial
    restart: always
    volumes:
      - $MONGODB_DATA_DIR:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    expose:
      - 27017
      - 27018
      - 27019

  mongo-express:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD

  fluentd:
    image: fluentd:v1.6.2-1.0
    restart: always
    volumes:
      - $FLUENTD_CONFIG_DIR:/fluentd/etc
    command: -v
    environment:
      MONGODB_USERNAME: $MONGODB_USERNAME
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    depends_on:
      - mongodb
    expose:
      - 24224
    
  txlogging:
    build: .
    restart: always
    depends_on:
      - fluentd
      - mongodb
    environment:
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      FLUENTD_APP: txlogging
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: txlogging
      MONGODB_COLLECTION: log
      MONGODB_USERNAME: $MONGODB_USERNAME
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    ports:
      - $TXQUEUE_PORT:8080

    
    
volumes:
  logvolume01: {}
