version: '3'
services:
  pdsdpi-mock-fhir-mongodb:
    build:
      context: mongodb
    restart: always
    volumes:
      - $MONGODB_DATA_VOLUME:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    expose:
      - 27017
      - 27018
      - 27019

  # pdsdpi-mock-fhir-mongo-express:
  #   image: mongo-express:0.49.0
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: pdsdpi-mock-fhir-mongodb
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD

  pdsdpi-mock-fhir:
    build: .
    restart: always
    depends_on:
      - pdsdpi-mock-fhir-mongodb
    environment:
      MONGO_HOST: pdsdpi-mock-fhir-mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    ports:
      - $API_PORT:8080

