version: '3'
services:
  pdspi-fhir-example-mongodb:
    image: txscience/tx-persistence:unstable
    restart: always
    volumes:
      - $MONGODB_DATA_VOLUME:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD

  pdspi-fhir-example:
    build: .
    restart: always
    depends_on:
      - pdspi-fhir-example-mongodb
    environment:
      MONGO_HOST: pdspi-fhir-example-mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
      FHIR_SERVER_URL_BASE: $FHIR_SERVER_URL_BASE
    ports:
      - $API_PORT:8080

