openapi: 3.0.0
info:
  version: '1'
  title: 'mock FHIR'
  description: 'mock FHIR'
paths: 
  /Patient/{patient_id}:
    get:
      operationId: api.get_patient
      parameters:
        - name: patient_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            appliation/json:
              schema:
                type: object
        404:
          description: resource not found
  /Obervation:
    get:
      operationId: api.get_observation
      parameters: 
        - name: patient_id
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /Condition:
    get:
      operationId: api.get_condition
      parameters: 
        - name: patient_id
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  
       
