openapi: 3.0.0
info:
  version: '1'
  title: 'mock FHIR'
  description: 'mock FHIR'
servers:
  - url: {{ server_url }}
paths: 
  /resource:
    delete:
      operationId: api.delete_resource
      responses:
        200:
          description: success operation
  /Bundle:
    post:
      operationId: api.post_bundle
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bundle"
      responses:
        200:
          description: success operation
  /Patient/{patient_id}:
    get:
      operationId: api.get_patient
      parameters:
        - name: patient_id
          example: 38
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Patient"
        404:
          description: resource not found
  /Patient:
    post:
      operationId: api.post_patient
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Patient"
      responses:
        200:
          description: success operation
  /Observation:
    get:
      operationId: api.get_observation
      parameters: 
        - name: patient
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Observation"
    post:
      operationId: api.post_observation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Observation"
      responses:
        200:
          description: success operation
  /Condition:
    get:
      operationId: api.get_condition
      parameters: 
        - name: patient
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: success operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Condition"
    post:
      operationId: api.post_condition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Condition'
      responses:
        200:
          description: success operation
components:
  schemas:
    Bundle:
      type: object
      properties:
        entry:
          type: array
          items:
            type: object
            properties:
              resource:
                anyOf:
                  - $ref: '#/components/schemas/Patient'
                  - $ref: '#/components/schemas/Observation'
                  - $ref: '#/components/schemas/Condition'
            required: ["resource"]
      required: ["entry"]
    Patient:
      type: object
      properties:
        id:
          type: string
          example: 38
        resourceType:
          type: string
          example: "Observation"
      required: ["id", "resourceType"]
    Observation:
      type: object
      properties:
        resourceType:
          type: string
        subject:
          type: object
          properties:
            reference:
              type: string
          required: ["reference"]
      required: ["resourceType", "subject"]
    Condition:
      type: object
      properties:
        resourceType:
          type: string
        subject:
          type: object
          properties:
            reference:
              type: string
          required: ["reference"]
      required: ["resourceType", "subject"]


